export const REQUEST_AQI = 'REQUEST_AQI';
export const SET_AQI_LIST = 'SET_AQI_LIST';
export const SET_CURRENT_COUNTY = 'SET_CURRENT_COUNTY';
export const SET_CURRENT_SORT_TYPE = 'SET_CURRENT_SORT_TYPE';